app = "hn-ceramic"
primary_region = "atl"

[build]
  image = "ceramicnetwork/js-ceramic:102d357c5b49fcf7bf1f613569f27148f9aa3fd8"
  swap_size_mb = 1024

[vm]
  size = "shared-cpu-2x"
  memory = "8gb"
  cpus = 4
  cpu_kind = "performance"
  processes = ["app"]

[http_service]
  internal_port = 7007
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]